spring.application.name=agendador-tarefas
spring.data.mongodb.uri=mongodb://localhost:27017/db_agendador
#spring.mongodb.uri=mongodb://localhost:27017/db_agendador  <<< PARA SPRING ACIMA DE 4.0.0
usuario.url=localhost:8080

server.port=8081
